services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
services:
  - name: web
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT main:app
